name: Actions Workflow

# on: [push, pull_request]
# on: [pull_request]
# on:
  # push:
    # pull_request:
      # types: [opened, synchronize]
      # types: [opened, synchronize, reopened, assigned, closed]

on: 
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
      types: [opened, synchronize]

jobs:
  run-github-actions:
    runs-on:  ubuntu-18.04
    steps:
      - name: list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -a
      - name: simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Varian Hermianto
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
