name: Shell Commands

on: [push]

jobs:
  run-github-actions:
    runs-on:  ubuntu-18.04
    steps:
      - name: simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Varian Hermianto
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
