name: ENV Variables

on: 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize]

env:
  WF_ENV: ${{ secrets.WF_ENV }}

jobs:
  log-env:
    runs-on:  ubuntu-18.04
    env:
      JOB_ENV: Available to all steps in this run-github-actions job XYZ
    steps:
      - name: log ENV variables
        env:
          STEP_ENV: Available to only this step XYZ
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
