name: Shell Commands

# on: [push, pull_request]
# on: [pull_request]
# on:
  # push:
    # pull_request:
      # types: [opened, synchronize]
      # types: [opened, synchronize, reopened, assigned, closed]

on: 
  # schedule:
    # - cron: "0/5 * * * *"
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize]

env:
  WF_ENV: Available to all jobs

jobs:
  run-shell-command:
    runs-on:  ubuntu-18.04
    # need: ['nama-jobs-sebelumnya']
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: check current directory bash
        run: pwd
        shell: bash
