name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on:  ubuntu-18.04
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: check current directory bash
        run: pwd
        shell: bash
